creation_rules:
  - plugin:
      - plugin_name: suffix
        configuration:
          suffix: "tatataatatayoohh"
      - plugin_name: scw
        configuration:
          id: c5782ccc-5498-400c-901d-15df9d3dabd8
          region: fr-par
          associated_data: aGVsbG8=
