syntax = "proto3";

package plugin.v1;

import "google/protobuf/struct.proto";

option go_package = "./plugin";

message EncryptRequest {
  optional bytes plaintext = 1;
  google.protobuf.Struct configuration = 2;
}

message EncryptResponse {
  optional bytes ciphertext = 1;
  Error error = 2;
}

message DecryptRequest {
  optional bytes ciphertext = 1;
  google.protobuf.Struct configuration = 2;
}

message DecryptResponse {
  optional bytes plaintext = 1;
  Error error = 2;
}

message Error {
  Code code = 1;
  string message = 2;
}

// Matches google.rpc.Code.
enum Code {
  CODE_UNSPECIFIED = 0;
  CODE_CANCELED = 1;
  CODE_UNKNOWN = 2;
  CODE_INVALID_ARGUMENT = 3;
  CODE_DEADLINE_EXCEEDED = 4;
  CODE_NOT_FOUND = 5;
  CODE_ALREADY_EXISTS = 6;
  CODE_PERMISSION_DENIED = 7;
  CODE_RESOURCE_EXHAUSTED = 8;
  CODE_FAILED_PRECONDITION = 9;
  CODE_ABORTED = 10;
  CODE_OUT_OF_RANGE = 11;
  CODE_UNIMPLEMENTED = 12;
  CODE_INTERNAL = 13;
  CODE_UNAVAILABLE = 14;
  CODE_DATA_LOSS = 15;
  CODE_UNAUTHENTICATED = 16;
  CODE_OK = 17;
}
